import {db,collection,doc,getDocs,setDoc,serverTimestamp} from "./firebase.js";
const $=id=>document.getElementById(id);
let players=[],awards=[],calculatedPlayer=null;
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const n=v=>Number(v||0), sr=p=>n(p.totalBalls)?n(p.totalRuns)/n(p.totalBalls)*100:0;
const eco=p=>n(p.totalBowlingBalls)?n(p.totalBowlingRuns)/(n(p.totalBowlingBalls)/6):0;
const ht=p=>n(p.bowlingHatTricks)+n(p.battingHatTricks)+n(p.fieldingHatTricks);
const awardsList=[
["SERIES_MOTM","ম্যান অব দ্য সিরিজ"],["FINAL_MOTM","ফাইনাল ম্যান অব দ্য ম্যাচ"],["MATCH_MOTM","প্রতিটা ম্যাচের ম্যান অব দ্য ম্যাচ"],
["BEST_BATSMAN","সেরা ব্যাটসম্যান"],["BEST_BOWLER","সেরা বোলার"],["BEST_ALLROUNDER","সেরা অলরাউন্ডার"],
["BEST_WICKETKEEPER","সেরা উইকেটকিপার"],["BEST_FIELDER","সেরা ফিল্ডার"],["MOST_RUNS","সর্বোচ্চ রান সংগ্রাহক"],
["MOST_WICKETS","সর্বোচ্চ উইকেট সংগ্রাহক"],["EMERGING","উদীয়মান খেলোয়াড়"],["HAT_TRICK","হ্যাটট্রিক পুরস্কার"],
["CENTURY","শতরান পুরস্কার"],["FIFTY","অর্ধশতরান পুরস্কার"],["BEST_CATCH","সেরা ক্যাচ"],["BEST_RUN_OUT","সেরা রান-আউট"],
["BEST_BOWLING_SPELL","সেরা বোলিং স্পেল"],["BEST_BATTING_INNINGS","সেরা ব্যাটিং ইনিংস"],["MOST_SIXES","সর্বাধিক ছক্কা"],
["FAIR_PLAY","Fair Play Trophy"],["TEAM_SPIRIT","Best Team Spirit Award"],["BEST_CAPTAIN","Best Captain Award"],
["SUPPORTED_TEAM","Best Supported Team Award"],["SF1_MOTM","সেমিফাইনাল–১ ম্যান অব দ্য ম্যাচ"],
["SF2_MOTM","সেমিফাইনাল–২ ম্যান অব দ্য ম্যাচ"],["TOURNAMENT_MOMENT","Moment of the Tournament"],["CUSTOM","Custom Award"]];
function rec(p){return {runs:n(p.totalRuns),balls:n(p.totalBalls),fours:n(p.totalFours),sixes:n(p.totalSixes),wickets:n(p.totalWickets),bowlingRuns:n(p.totalBowlingRuns),bowlingBalls:n(p.totalBowlingBalls),economy:eco(p),strikeRate:sr(p),catches:n(p.fieldingCatches),stumpings:n(p.fieldingStumpings),runOuts:n(p.fieldingRunOuts),fieldingDismissals:n(p.fieldingDismissals)||n(p.fieldingCatches)+n(p.fieldingStumpings)+n(p.fieldingRunOuts),hatTricks:ht(p),centuries:n(p.centuries),fifties:n(p.fifties)}}
function recordHtml(p){const r=rec(p),items=[["Runs",r.runs],["Balls",r.balls],["SR",r.strikeRate.toFixed(2)],["4s",r.fours],["6s",r.sixes],["Wickets",r.wickets],["Bowling Runs",r.bowlingRuns],["Bowling Balls",r.bowlingBalls],["Economy",r.economy.toFixed(2)],["Catches",r.catches],["Stumpings",r.stumpings],["Run Outs",r.runOuts],["Hat-tricks",r.hatTricks]];return items.map(([a,b])=>`<div class="record"><b>${esc(b)}</b><small>${a}</small></div>`).join("")}
function option(p){return `<option value="${esc(p.id)}">${esc(p.name||p.playerName||p.id)}${p.teamName?" — "+esc(p.teamName):""}</option>`}
function eligible(t,p){const r=rec(p);if(["BEST_BOWLER","MOST_WICKETS","BEST_BOWLING_SPELL"].includes(t))return r.bowlingBalls>0||r.wickets>0;if(["BEST_FIELDER","BEST_CATCH","BEST_RUN_OUT"].includes(t))return r.fieldingDismissals>0;if(t==="BEST_WICKETKEEPER")return r.catches>0||r.stumpings>0;if(t==="HAT_TRICK")return r.hatTricks>0;if(t==="CENTURY")return r.centuries>0||r.runs>=100;if(t==="FIFTY")return r.fifties>0||r.runs>=50;if(["BEST_BATSMAN","MOST_RUNS","MOST_SIXES","BEST_BATTING_INNINGS"].includes(t))return r.balls>0||r.runs>0;return r.runs>0||r.wickets>0||r.fieldingDismissals>0}
function score(t,p){const r=rec(p);switch(t){case"MOST_RUNS":return r.runs*1e5+r.balls;case"MOST_WICKETS":return r.wickets*1e5-r.economy;case"MOST_SIXES":return r.sixes*1e5+r.runs;case"HAT_TRICK":return r.hatTricks*1e5+r.wickets;case"CENTURY":return r.centuries*1e5+r.runs;case"FIFTY":return r.fifties*1e5+r.runs;case"BEST_BATSMAN":return r.runs+r.sixes*3+r.fours*2+r.strikeRate*.5;case"BEST_BOWLER":return r.wickets*100-r.economy*2+r.bowlingBalls*.05;case"BEST_ALLROUNDER":return r.runs+r.wickets*20+r.fieldingDismissals*5;case"BEST_WICKETKEEPER":return r.stumpings*30+r.catches*10+r.runs*.2;case"BEST_FIELDER":return r.catches*20+r.runOuts*20+r.stumpings*15;case"BEST_CATCH":return r.catches*1000+r.fieldingDismissals;case"BEST_RUN_OUT":return r.runOuts*1000+r.fieldingDismissals;case"BEST_BOWLING_SPELL":return r.wickets*100-r.bowlingRuns+r.bowlingBalls*.1;case"BEST_BATTING_INNINGS":return r.runs+r.sixes*3+r.fours*2;default:return r.runs+r.wickets*20+r.fieldingDismissals*10+r.sixes*2}}
function renderStats(){const a=[...players].sort((x,y)=>n(y.totalRuns)-n(x.totalRuns));$("statsTable").innerHTML=a.length?`<div class="table-wrap"><table><tr><th>Player</th><th>Team</th><th>Runs</th><th>Balls</th><th>SR</th><th>4s</th><th>6s</th><th>Wickets</th><th>Bowling Runs</th><th>Economy</th><th>Fielding</th><th>Hat-tricks</th></tr>${a.map(p=>{let r=rec(p);return `<tr><td>${esc(p.name||p.playerName||p.id)}</td><td>${esc(p.teamName||"")}</td><td>${r.runs}</td><td>${r.balls}</td><td>${r.strikeRate.toFixed(2)}</td><td>${r.fours}</td><td>${r.sixes}</td><td>${r.wickets}</td><td>${r.bowlingRuns}</td><td>${r.economy.toFixed(2)}</td><td>${r.fieldingDismissals}</td><td>${r.hatTricks}</td></tr>`}).join("")}</table></div>`:"কোনো player record পাওয়া যায়নি।"}
function renderSelect(){let s=$("awardPlayer"),old=s.value;s.innerHTML='<option value="">Player নির্বাচন করুন</option>'+players.map(option).join("");if(players.some(p=>p.id===old))s.value=old}
function choose(id){let p=players.find(x=>x.id===id);if(!p)return;calculatedPlayer=p;$("awardPlayer").value=p.id;$("awardResult").classList.remove("hidden");$("calculatedPlayer").innerHTML=`<b>${esc(p.name||p.playerName||p.id)}</b> ${esc(p.teamName||"")}`;$("calculatedRecord").innerHTML=recordHtml(p);$("awardMsg").textContent="Player নির্বাচিত হয়েছে। Save Award চাপুন।";renderRows()}
function renderRows(){let t=$("awardType").value,good=players.filter(p=>eligible(t,p)),rows=(good.length?good:[...players]).sort((a,b)=>score(t,b)-score(t,a));$("calculatedPlayers").innerHTML=rows.length?`<div class="calc-head"><b>${esc($("awardType").selectedOptions[0]?.textContent||t)}</b><span>${rows.length} জন player</span></div><div class="player-cards">${rows.map((p,i)=>`<article class="player-card ${i===0?"recommended":""}"><div class="player-top"><div><div class="rank">#${i+1}${i===0?" • Recommended":""}</div><h3>${esc(p.name||p.playerName||p.id)}</h3><div class="team">${esc(p.teamName||"")}</div></div><button type="button" class="choose-player" data-id="${esc(p.id)}">Select</button></div><div class="record-grid">${recordHtml(p)}</div></article>`).join("")}</div>`:"কোনো player record পাওয়া যায়নি।";$("calculatedPlayers").querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>choose(b.dataset.id))}
function calculate(){if(!players.length){$("calcMsg").textContent="Player data load হয়নি। Player Records-এর error দেখুন।";return}let t=$("awardType").value,good=players.filter(p=>eligible(t,p)),rows=(good.length?good:[...players]).sort((a,b)=>score(t,b)-score(t,a));$("calcMsg").textContent=`${rows.length} জন player-এর record calculate হয়েছে।`;if(rows[0])choose(rows[0].id);renderRows()}
async function loadPlayers(){ $("statsTable").textContent="Player records load হচ্ছে...";try{let s=await getDocs(collection(db,"players"));players=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||a.playerName||"").localeCompare(b.name||b.playerName||""));renderSelect();renderStats();$("calcMsg").textContent=players.length?`${players.length} জন player load হয়েছে।`:"players collection-এ কোনো document নেই।"}catch(e){console.error(e);$("statsTable").innerHTML=`<p class="error">Player load error: ${esc(e.code||e.message)}</p>`;$("calcMsg").textContent="Firestore Rules-এ players read permission পরীক্ষা করুন।";$("awardPlayer").innerHTML='<option value="">Player load failed</option>'}}
async function loadAwards(){try{let s=await getDocs(collection(db,"awards"));awards=s.docs.map(d=>({id:d.id,...d.data()}));$("awardTable").innerHTML=awards.length?`<div class="table-wrap"><table><tr><th>Season</th><th>Award</th><th>Player</th><th>Team</th><th>Prize</th><th>Record</th><th>Note</th></tr>${awards.map(a=>{let r=a.recordSnapshot||{};return `<tr><td>${esc(a.season||"")}</td><td>${esc(a.awardName||"")}</td><td>${esc(a.playerName||"")}</td><td>${esc(a.teamName||"")}</td><td>${esc(a.prize||"")}</td><td>${r.runs||0} R • ${r.wickets||0} W</td><td>${esc(a.note||"")}</td></tr>`}).join("")}</table></div>`:"এখনও কোনো award save হয়নি।"}catch(e){console.error(e);$("awardTable").innerHTML=`<p class="error">Saved Awards load error: ${esc(e.code||e.message)}. Player calculation আলাদাভাবে চলবে।</p>`}}
$("awardType").innerHTML=awardsList.map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join("");
$("calculateAward").onclick=calculate;
$("awardType").onchange=()=>{$("awardResult").classList.add("hidden");$("calculatedPlayers").innerHTML="";$("calcMsg").textContent="";calculatedPlayer=null};
$("awardPlayer").onchange=()=>{if($("awardPlayer").value)choose($("awardPlayer").value)};
$("saveAward").onclick=async()=>{let p=players.find(x=>x.id===$("awardPlayer").value);if(!p){$("awardMsg").textContent="Player নির্বাচন করুন।";return}let t=$("awardType").value,label=$("awardType").selectedOptions[0]?.textContent||t,custom=$("awardCustomName").value.trim(),name=t==="CUSTOM"?custom:(custom||label);if(!name){$("awardMsg").textContent="Award-এর নাম দিন।";return}let season=Number($("awardSeason").value||2026),id=`award-${season}-${Date.now()}`;$("saveAward").disabled=true;try{await setDoc(doc(db,"awards",id),{id,season,awardName:name,awardType:t,playerId:p.id,playerName:p.name||p.playerName||p.id,teamId:p.teamId||"",teamName:p.teamName||"",prize:$("awardPrize").value.trim(),note:$("awardNote").value.trim(),recordSnapshot:rec(p),public:true,calculatedBy:"VCAJ Awards Calculator",createdAt:serverTimestamp()});$("awardMsg").textContent="Award save হয়েছে।";$("awardPrize").value="";$("awardNote").value="";$("awardCustomName").value="";await loadAwards()}catch(e){console.error(e);$("awardMsg").textContent=`Save error: ${e.code||e.message}. Firestore Rules পরীক্ষা করুন।`}finally{$("saveAward").disabled=false}};
await Promise.allSettled([loadPlayers(),loadAwards()]);
