import {auth,db,isAdmin,collection,doc,getDocs,getDoc,setDoc,onAuthStateChanged,signInWithEmailAndPassword,serverTimestamp} from './firebase.js';
const $=id=>document.getElementById(id);let teams=[],players=[],current={slots:Array(16).fill(''),winners:{},matchIds:{},championTeamId:''};let user=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function loadData(){const [ts,ps]=await Promise.all([getDocs(collection(db,'teams')),getDocs(collection(db,'players'))]);teams=ts.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||'').localeCompare(b.name||''));players=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||'').localeCompare(b.name||''));renderSlots();renderTeamTools();}
async function loadSeason(){const s=await getDoc(doc(db,'tournaments',String($('season').value)));current=s.exists()?{...current,...s.data()}:{slots:Array(16).fill(''),winners:{},matchIds:{}};current.slots=(current.slots||Array(16).fill('')).slice(0,16);while(current.slots.length<16)current.slots.push('');current.winners=current.winners||{};current.matchIds=current.matchIds||{};renderSlots();renderBracket();}
function renderSlots(){const used=new Set(current.slots.filter(Boolean));$('slots').innerHTML=current.slots.map((id,i)=>`<div><label>Seed ${i+1}</label><select data-slot="${i}"><option value="">দল নির্বাচন</option>${teams.map(t=>`<option value="${esc(t.id)}" ${id===t.id?'selected':''} ${used.has(t.id)&&id!==t.id?'disabled':''}>${esc(t.name)}</option>`).join('')}</select></div>`).join('');}
function renderTeamTools(){const sel=$('quickPlayerTeam');if(sel){sel.innerHTML=`<option value="">দল নির্বাচন করুন</option>${teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${players.filter(p=>p.teamId===t.id).length} players)</option>`).join('')}`;}if($('teamCount'))$('teamCount').textContent=`${teams.length} / 16 দল`;}
function teamName(id){return teams.find(t=>t.id===id)?.name||'TBD';}
function pair(stage,index,a,b){const key=`${stage}-${index}`,w=current.winners?.[key]||'',matchId=current.matchIds?.[key]||'';return `<div class="match-card"><div class="badge">${stage==='r16'?'R16':stage==='qf'?'Quarter Final':stage==='sf'?'Semi Final':'FINAL'} • ${index+1}</div><div class="team ${w===a&&a?'winner':''}"><span>${esc(teamName(a))}</span><b>${w===a&&a?'✓':''}</b></div><div class="team ${w===b&&b?'winner':''}"><span>${esc(teamName(b))}</span><b>${w===b&&b?'✓':''}</b></div>${matchId?`<small class="muted">${esc(matchId)}</small>`:''}${a&&b&&!w?`<a class="button-link" href="scorer.html?stage=${stage.toUpperCase()}&bracket=${key}&t1=${encodeURIComponent(a)}&t2=${encodeURIComponent(b)}">Open Scorer</a>`:''}</div>`;}
function renderBracket(){const s=current.slots,r16=[],q=[],sf=[];for(let i=0;i<8;i++)r16.push(pair('r16',i,s[i*2],s[i*2+1]));for(let i=0;i<4;i++)q.push(pair('qf',i,current.winners?.[`r16-${i*2}`]||'',current.winners?.[`r16-${i*2+1}`]||''));for(let i=0;i<2;i++)sf.push(pair('sf',i,current.winners?.[`qf-${i*2}`]||'',current.winners?.[`qf-${i*2+1}`]||''));const fin=pair('final',0,current.winners?.['sf-0']||'',current.winners?.['sf-1']||'');const champ=current.championTeamId?teamName(current.championTeamId):'';$('bracket').innerHTML=`<div class="round"><h3>Round of 16</h3>${r16.join('')}</div><div class="round"><h3>Quarter Final</h3>${q.join('')}</div><div class="round"><h3>Semi Final</h3>${sf.join('')}</div><div class="round"><h3>Final</h3>${fin}${champ?`<div class="champion">🏆 Champion: <b>${esc(champ)}</b></div>`:''}</div>`;}
$('load').onclick=loadSeason;
$('refresh').onclick=loadData;
$('save').onclick=async()=>{if(!isAdmin(user)){alert('Admin login করুন।');return;}document.querySelectorAll('[data-slot]').forEach(s=>current.slots[Number(s.dataset.slot)]=s.value);const filled=new Set(current.slots.filter(Boolean));if(filled.size<2){$('msg').textContent='কমপক্ষে ২টি দল নির্বাচন করুন।';return;}await setDoc(doc(db,'tournaments',String($('season').value)),{season:Number($('season').value),slots:current.slots,winners:current.winners||{},matchIds:current.matchIds||{},championTeamId:current.championTeamId||'',updatedAt:serverTimestamp()},{merge:true});$('msg').textContent='Bracket saved.';renderBracket();};
$('clear').onclick=()=>{if(!isAdmin(user)){alert('Admin login করুন।');return;}current.slots=Array(16).fill('');current.winners={};current.matchIds={};current.championTeamId='';renderSlots();renderBracket();};
$('login').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(e){$('msg').textContent=e.message}};
$('addQuickTeam').onclick=async()=>{if(!isAdmin(user)){alert('Admin login করুন।');return;}const name=$('quickTeamName').value.trim(),shortName=$('quickTeamShort').value.trim();if(!name){$('quickMsg').textContent='দলের নাম দিন।';return;}if(teams.length>=16){$('quickMsg').textContent='১৬টি দলের সীমা পূর্ণ হয়েছে।';return;}if(teams.some(t=>(t.name||'').trim().toLowerCase()===name.toLowerCase())){$('quickMsg').textContent='এই নামে দল আগে থেকেই আছে।';return;}const id=`team-${Date.now()}`;await setDoc(doc(db,'teams',id),{id,name,shortName,playersCount:0,season:Number($('season').value||2026),createdAt:serverTimestamp()});$('quickTeamName').value='';$('quickTeamShort').value='';$('quickMsg').textContent=`${name} দল তৈরি হয়েছে।`;await loadData();$('quickPlayerTeam').value=id;};
$('addQuickPlayer').onclick=async()=>{if(!isAdmin(user)){alert('Admin login করুন।');return;}const name=$('quickPlayerName').value.trim(),teamId=$('quickPlayerTeam').value;if(!name||!teamId){$('quickPlayerMsg').textContent='খেলোয়াড়ের নাম ও দল নির্বাচন করুন।';return;}const team=teams.find(t=>t.id===teamId);if(!team){$('quickPlayerMsg').textContent='দল পাওয়া যায়নি।';return;}if(players.some(p=>p.teamId===teamId&&(p.name||'').trim().toLowerCase()===name.toLowerCase())){$('quickPlayerMsg').textContent='এই দলের এই নামে খেলোয়াড় আগে থেকেই আছে।';return;}const id=`player-${Date.now()}`;await setDoc(doc(db,'players',id),{id,name,teamId,teamName:team.name,totalRuns:0,totalBalls:0,totalFours:0,totalSixes:0,totalMatches:0,totalWickets:0,fieldingCatches:0,fieldingStumpings:0,fieldingRunOuts:0,fieldingDismissals:0,createdAt:serverTimestamp()});await setDoc(doc(db,'teams',teamId),{playersCount:(team.playersCount||0)+1},{merge:true});$('quickPlayerName').value='';$('quickPlayerMsg').textContent=`${name} ${team.name}-এ যোগ হয়েছে।`;await loadData();$('quickPlayerTeam').value=teamId;};
onAuthStateChanged(auth,async u=>{user=u;if(u&&isAdmin(u)){$('loginState').textContent='Admin verified';$('loginBox').classList.add('hidden');$('adminTools').classList.remove('hidden')}else{$('loginState').textContent='Login required';$('loginBox').classList.remove('hidden');$('adminTools').classList.add('hidden')}await loadData();await loadSeason();});
