import {auth,db,isAdmin,collection,doc,getDoc,getDocs,setDoc,updateDoc,deleteDoc,signInWithEmailAndPassword,signOut,onAuthStateChanged,serverTimestamp} from './firebase.js';
const $=id=>document.getElementById(id);let members=[],teams=[],currentUser=null,editingId=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderAuth(){if(isAdmin(currentUser)){$('authBox').innerHTML='<strong>Admin mode চালু</strong> <button id="logoutBtn">Logout</button>';$('logoutBtn').onclick=()=>signOut(auth);$('memberFormCard').classList.remove('hidden');}else{$('authBox').innerHTML='<div class="toolbar"><input id="adminEmail" type="email" value="vcajofficial@gmail.com"><input id="adminPassword" type="password" placeholder="Admin password"><button id="loginBtn">Admin Login</button></div><p id="loginMsg" class="msg"></p>';$('loginBtn').onclick=login;$('memberFormCard').classList.add('hidden');}}
async function login(){try{await signInWithEmailAndPassword(auth,$('adminEmail').value.trim(),$('adminPassword').value);$('loginMsg').textContent='';}catch(e){$('loginMsg').textContent='Login হয়নি।';}}
async function load(){try{const ts=await getDocs(collection(db,'teams'));teams=ts.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||'').localeCompare(b.name||''));if(isAdmin(currentUser)){const ms=await getDocs(collection(db,'members'));members=ms.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||'').localeCompare(b.name||''));$('memberTeam').innerHTML='<option value="">দল নেই / প্রযোজ্য নয়</option>'+teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');renderAdmin();} }catch(e){$('members').innerHTML=`<p>${esc(e.message)}</p>`;}}
async function renderAdmin(){const box=$('members');box.innerHTML=members.length?`<table><tr><th>Member ID</th><th>নাম</th><th>ফোন</th><th>দল</th><th>Paid</th><th>Status</th><th>Action</th></tr>${members.map(m=>`<tr><td>${esc(m.id)}</td><td>${esc(m.name)}</td><td>${esc(m.phone)}</td><td>${esc(m.teamName)}</td><td>₹ ${esc(m.fee||0)}</td><td>${esc(m.feeStatus||'')}</td><td><button data-edit="${esc(m.id)}">Edit</button> <button data-delete="${esc(m.id)}">Delete</button></td></tr>`).join('')}</table>`:'<p>এখনও কোনো সদস্য নেই।';$('memberCount').textContent=`${members.length} জন`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>startEdit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeMember(b.dataset.delete));}
function resetForm(){editingId=null;$('formTitle').textContent='নতুন সদস্য যোগ করুন';$('saveMember').textContent='সদস্য Save করুন';$('cancelEdit').classList.add('hidden');['memberName','memberRole','memberPhone','memberEmail','memberAddress','memberFee','memberNote'].forEach(id=>$(id).value='');$('memberFeeStatus').value='বাকি';$('memberSeason').value='2026';$('memberTeam').value='';$('memberMsg').textContent='';}
function startEdit(id){const m=members.find(x=>x.id===id);if(!m)return;editingId=id;$('formTitle').textContent='সদস্য Edit করুন';$('saveMember').textContent='পরিবর্তন Save করুন';$('cancelEdit').classList.remove('hidden');$('memberName').value=m.name||'';$('memberRole').value=m.role||'';$('memberPhone').value=m.phone||'';$('memberEmail').value=m.email||'';$('memberAddress').value=m.address||'';$('memberFee').value=m.fee||'';$('memberFeeStatus').value=m.feeStatus||'বাকি';$('memberSeason').value=m.season||'2026';$('memberNote').value=m.note||'';$('memberTeam').value=m.teamId||'';scrollTo({top:0,behavior:'smooth'});}
async function saveMember(){if(!isAdmin(currentUser))return;const name=$('memberName').value.trim();if(!name){$('memberMsg').textContent='সদস্যের নাম দিন।';return;}const team=teams.find(t=>t.id===$('memberTeam').value);const id=editingId||`member-${Date.now()}`;const data={id,name,role:$('memberRole').value.trim(),phone:$('memberPhone').value.trim(),email:$('memberEmail').value.trim().toLowerCase(),address:$('memberAddress').value.trim(),fee:$('memberFee').value.trim(),feeStatus:$('memberFeeStatus').value,season:Number($('memberSeason').value||2026),note:$('memberNote').value.trim(),teamId:team?.id||'',teamName:team?.name||'',updatedAt:serverTimestamp()};try{await setDoc(doc(db,'members',id),{...data,...(!editingId?{createdAt:serverTimestamp()}:{} )},{merge:true});await setDoc(doc(db,'memberDirectory',id),{memberId:id,name:data.name,role:data.role,teamName:data.teamName,paidAmount:data.fee||0,paymentStatus:data.feeStatus||'',season:data.season,updatedAt:serverTimestamp()});$('memberMsg').textContent='সদস্য Save হয়েছে এবং public list update হয়েছে।';resetForm();await load();}catch(e){$('memberMsg').textContent='Save হয়নি: '+e.message;}}
async function removeMember(id){if(!confirm('এই সদস্যকে Delete করতে চান?'))return;try{await deleteDoc(doc(db,'members',id));await deleteDoc(doc(db,'memberDirectory',id));await load();}catch(e){alert('Delete হয়নি: '+e.message);}}
$('saveMember').onclick=saveMember;$('cancelEdit').onclick=resetForm;$('refresh').onclick=load;onAuthStateChanged(auth,u=>{currentUser=u;renderAuth();renderAdmin();load();});
