import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut as signOutSecondary} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {auth,db,isAdmin,doc,getDocs,collection,setDoc,serverTimestamp,onAuthStateChanged} from './firebase.js';
import {firebaseConfig} from './firebase-config.js';
const $=id=>document.getElementById(id); const secondaryApp=initializeApp(firebaseConfig,'memberAccountSetup'); const secondaryAuth=getAuth(secondaryApp);
const phoneDigits=p=>String(p||'').replace(/\D/g,''); const phoneToAuthEmail=p=>`m${phoneDigits(p)}@member.vcajcricket.com`;
function initialPassword(m){const prefix=String(m.email||'').split('@')[0].replace(/[^a-zA-Z]/g,'').slice(0,4).toLowerCase();return `${prefix}@${phoneDigits(m.phone).slice(-4)}`;}
$('adminLogin').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('adminEmail').value.trim(),$('adminPassword').value);$('loginMsg').textContent='';}catch(e){$('loginMsg').textContent='Admin Login হয়নি।';}};
onAuthStateChanged(auth,user=>{if(user&&isAdmin(user)){$('loginCard').classList.add('hidden');$('setupCard').classList.remove('hidden');}else{$('loginCard').classList.remove('hidden');$('setupCard').classList.add('hidden');}});
async function createAccount(m,password){const authEmail=phoneToAuthEmail(m.phone);let cred;try{cred=await createUserWithEmailAndPassword(secondaryAuth,authEmail,password);}catch(e){if(e.code==='auth/email-already-in-use') throw new Error('AUTH_EXISTS');throw e;}const uid=cred.user.uid;await setDoc(doc(db,'memberAccounts',uid),{memberId:m.id,phone:m.phone,contactEmail:m.email||'',authEmail,mustChangePassword:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});return {uid,authEmail,password};}
$('createAll').onclick=async()=>{if(!isAdmin(auth.currentUser))return;$('createAll').disabled=true;$('progress').innerHTML='';let snap;try{snap=await getDocs(collection(db,'members'));}catch(e){$('setupMsg').textContent='Members collection পড়া যায়নি।';$('createAll').disabled=false;return;}const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(m=>m.phone&&m.email);$('count').textContent=`${rows.length} জন`;let ok=0,fail=0;for(const m of rows){const password=initialPassword(m);const row=document.createElement('div');row.className='msg';row.textContent=`${m.id} • ${m.name||''} — তৈরি হচ্ছে...`;$('progress').appendChild(row);try{await createAccount(m,password);ok++;row.innerHTML=`✓ <strong>${m.id} • ${m.name||''}</strong> — Ready <span class="muted">Initial password: ${password}</span>`;}catch(e){fail++;row.textContent=e.message==='AUTH_EXISTS'?`• ${m.id} • ${m.name||''} — account আগে থেকেই আছে (নতুন password reset করা হয়নি)`:`✗ ${m.id} • ${m.name||''} — account তৈরি হয়নি`;}}try{await signOutSecondary(secondaryAuth);}catch(e){}$('setupMsg').textContent=`সম্পন্ন: ${ok}টি নতুন account, ${fail}টি skipped/failed।`;$('createAll').disabled=false;};
