import {db,collection,getDocs,doc,getDoc} from './firebase.js';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const labels={bestBatsman:['🏏','Best Batsman'],bestBowler:['🎯','Best Bowler'],bestKeeper:['🧤','Best Wicketkeeper'],bestFielder:['⚡','Best Fielder'],playerOfTournament:['⭐','Player of the Tournament']};
const matchLabels={bestBatsman:['🏏','Best Batsman'],bestBowler:['🎯','Best Bowler'],bestKeeper:['🧤','Best Wicketkeeper'],bestFielder:['⚡','Best Fielder'],manOfMatch:['⭐','Man of the Match']};
function n(v){return Number(v||0)}
function metrics(v){if(!v)return '';return v.metrics||v.note||''}
async function getTeams(){const s=await getDocs(collection(db,'teams'));return Object.fromEntries(s.docs.map(d=>[d.id,{id:d.id,...d.data()}]));}
async function load(){const season=n($('season').value||2026);$('status').textContent='লোড হচ্ছে…';try{const [tSnap,ms,teams]=await Promise.all([getDoc(doc(db,'tournaments',String(season))),getDocs(collection(db,'matches')),getTeams()]);const t=tSnap.exists()?tSnap.data():{};renderTournament(t,teams);const matches=ms.docs.map(d=>({id:d.id,...d.data()})).filter(m=>n(m.season)===season).sort((a,b)=>String(a.stage||a.stageName||'').localeCompare(String(b.stage||b.stageName||'')));renderMatches(matches);$('status').textContent=`${season} season`; }catch(e){console.error(e);$('status').textContent='লোড করতে সমস্যা হয়েছে';}}
function renderTournament(t,teams){const champ=t.championTeamId?teams[t.championTeamId]:null;$('championWrap').innerHTML=champ?`<section class="card champion"><div class="icon">🏆</div><h2>Season Champion</h2><div class="winner">${esc(champ.name||champ.teamName||champ.id)}</div><div class="metric">${esc(t.season||'')} Tournament Champion</div></section>`:'<div class="notice">🏆 এই season-এর Champion এখনও ঘোষণা করা হয়নি।</div>';
const a=t.awards||{};$('tournamentAwards').innerHTML=Object.keys(labels).map(k=>{const v=a[k];const [icon,label]=labels[k];return `<article class="award-card"><div class="icon">${icon}</div><h3>${label}</h3>${v?.playerName?`<div class="winner">${esc(v.playerName)}</div><div class="metric">${esc(metrics(v))}</div>`:'<div class="muted">Award এখনও ঘোষণা করা হয়নি।</div>'}</article>`}).join('');}
function renderMatches(matches){$('matchCount').textContent=`${matches.length} ম্যাচ`;if(!matches.length){$('matchesList').innerHTML='<div class="empty">এই season-এ এখনও কোনো match পাওয়া যায়নি।</div>';return;}$('matchesList').innerHTML=matches.map((m,i)=>{const a=m.awards||{};const title=m.title||`${m.team1Name||''} vs ${m.team2Name||''}`;const cards=Object.keys(matchLabels).map(k=>{const v=a[k];const [icon,label]=matchLabels[k];return `<div class="mini-award"><b>${icon} ${label}</b>${v?.playerName?`<div>${esc(v.playerName)}</div><small class="muted">${esc(metrics(v))}</small>`:'<small class="muted">এখনও ঘোষণা হয়নি</small>'}</div>`}).join('');return `<article class="match-card"><div class="match-head"><h3>${i+1}. ${esc(title)}</h3><small class="muted">${esc(m.stageName||m.stage||'')}</small></div><div class="match-awards">${cards}</div></article>`}).join('');}
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('tournamentTab').classList.toggle('hidden',btn.dataset.tab!=='tournament');$('matchesTab').classList.toggle('hidden',btn.dataset.tab!=='matches');});
$('season').onchange=load;load();


async function loadHatTrickRecords(){
 const season=Number(document.getElementById('season').value||2026);const ms=await getDocs(collection(db,'matches'));const rows=[];
 for(const d of ms.docs){const m=d.data();if(Number(m.season)!==season||!m.hatTricks)continue;const h=m.hatTricks;for(const type of ['bowler','batter','fielder'])for(const x of (h[type]||[]))rows.push({...x,type,match:m.title||d.id});}
 const labels={bowler:['🎯','Bowler Hat-trick'],batter:['🏏','Batting Hat-trick'],fielder:['⚡','Fielding Hat-trick']};
 document.getElementById('hatTrickRecords').innerHTML=rows.map(x=>`<div class="award-card"><div class="icon">${labels[x.type][0]}</div><h3>${labels[x.type][1]}</h3><div class="winner">${esc(x.playerName)}</div><div class="metric">${esc(x.match)} • ${esc(x.over||'')} • Innings ${x.inningsNo||1}</div></div>`).join('')||'<div class="empty">এই season-এ এখনও কোনো hat-trick record নেই।</div>';
}
const _oldSeason=document.getElementById('season');if(_oldSeason)_oldSeason.addEventListener('change',()=>loadHatTrickRecords());loadHatTrickRecords();
