import {auth,db,isAdmin,collection,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,serverTimestamp,signInWithEmailAndPassword,signOut,onAuthStateChanged} from "./firebase.js";
const phoneToAuthEmail=phone=>`m${String(phone||'').replace(/\D/g,'')}@member.vcajcricket.com`;
const $=id=>document.getElementById(id); let state=null,unsub=null,eventStack=[]; let teams=[],players=[],members=[]; let editingMemberId="";
const stageNames={R16:"Round of 16",QF:"Quarter Final",SF:"Semi Final",FINAL:"Final",CUSTOM:"Custom"};
const bowlerWicketTypes=["bowled","caught","lbw","stumped","hitWicket"];
const dismissalNames={bowled:{bn:"বোল্ড",en:"Bowled"},caught:{bn:"ক্যাচ আউট",en:"Caught"},lbw:{bn:"LBW",en:"LBW"},runOut:{bn:"রান আউট",en:"Run Out"},stumped:{bn:"স্টাম্পড",en:"Stumped"},hitWicket:{bn:"হিট উইকেট",en:"Hit Wicket"},obstructing:{bn:"ফিল্ডে বাধা",en:"Obstructing the Field"},hitTwice:{bn:"দুবার বল মারা",en:"Hit the Ball Twice"},timedOut:{bn:"টাইমড আউট",en:"Timed Out"},retiredOut:{bn:"রিটায়ার্ড আউট",en:"Retired Out"}};
const slug=s=>(s||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,35);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
function ballsText(n){return `${Math.floor((n||0)/6)}.${(n||0)%6}`;}
function oversValue(){const v=$("overs").value;return v==="custom"?Number($("customOvers").value||15):Number(v);}
function clone(x){return JSON.parse(JSON.stringify(x));}
function makePlayers(list,teamId){return list.map(p=>({id:p.id,name:p.name,runs:0,balls:0,fours:0,sixes:0,out:false,teamId}));}
function makeBowlers(list,teamId){return list.map(p=>({id:p.id,name:p.name,balls:0,runs:0,wickets:0,teamId,fieldingCatches:0,fieldingStumpings:0,fieldingRunOuts:0}));}
function makeInnings(battingTeamId,battingTeam,bowlingTeamId,bowlingTeam,batList,bowlList,maxOvers,target=0,number=1,superOver=false){const p=makePlayers(batList,battingTeamId),b=makeBowlers(bowlList,bowlingTeamId);return {inningsNo:number,battingTeamId,battingTeam,bowlingTeamId,bowlingTeam,score:0,wickets:0,legalBalls:0,maxOvers,target,players:p,bowlers:b,striker:p[0]?.id||"",nonStriker:p[1]?.id||"",bowler:b[0]?.id||"",freeHit:false,bowlerChangeRequired:false,bowlerChangeFromId:"",extras:{wide:0,noBall:0,bye:0,legBye:0},commentary:[],status:"LIVE",superOver};}
function newMatch(id,t1,t2,overs,team1Players,team2Players,meta){const inn=makeInnings(t1,meta.team1Name,t2,meta.team2Name,team1Players,team2Players,overs,0,1,false);return {version:3,id,title:`${meta.team1Name} vs ${meta.team2Name} — ${meta.stageName}`,season:Number(meta.season)||2026,stage:meta.stage,stageName:meta.stageName,bracketKey:meta.bracketKey||"",team1Id:t1,team2Id:t2,team1Name:meta.team1Name,team2Name:meta.team2Name,maxOvers:overs,inningsNo:1,inningsHistory:[],superOver:null,winnerTeamId:"",winnerTeamName:"",resultText:"",status:"LIVE",...inn};}
function current(){return state;}
const LOCAL_PREFIX='vcaj_match_backup_v1_';
const PENDING_PREFIX='vcaj_pending_events_v1_';
let cloudOnline=navigator.onLine;
function localKey(id){return LOCAL_PREFIX+String(id||'unknown');}
function pendingKey(id){return PENDING_PREFIX+String(id||'unknown');}
function persistLocalState(){
  if(!state?.id)return;
  try{
    const safe=JSON.parse(JSON.stringify({...state,updatedAt:Date.now()}));
    localStorage.setItem(localKey(state.id),JSON.stringify(safe));
    localStorage.setItem('vcajActiveMatchId',state.id);
  }catch(e){console.warn('Local backup failed',e);}
}
function readLocalState(id){try{const x=localStorage.getItem(localKey(id));return x?JSON.parse(x):null;}catch(e){return null;}}
function pendingEvents(){try{return JSON.parse(localStorage.getItem(pendingKey(state?.id))||'[]');}catch(e){return[];}}
function writePendingEvents(list){if(state?.id)localStorage.setItem(pendingKey(state.id),JSON.stringify(list));}
function queueEvent(ev){const list=pendingEvents();if(!list.some(x=>x.eventId===ev.eventId))list.push(ev);writePendingEvents(list);}
function newEventId(){return `evt-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
function setNetworkBadge(){
  let el=document.getElementById('syncStatus');
  if(!el)return;
  const pending=pendingEvents().length;
  el.textContent=!navigator.onLine?`OFFLINE • Local backup ON${pending?` • ${pending} pending`:''}`:pending?`ONLINE • ${pending} pending sync`:'ONLINE • Saved to Firebase';
  el.className='pill '+(!navigator.onLine?'danger-pill':pending?'warn-pill':'ok-pill');
}
async function syncEvent(ev){
  try{await setDoc(doc(db,'matches',state.id,'events',ev.eventId),ev);return true;}catch(e){cloudOnline=false;queueEvent(ev);setNetworkBadge();return false;}
}
async function syncPending(){
  if(!state?.id||!navigator.onLine)return;
  const list=pendingEvents();if(!list.length){setNetworkBadge();return;}
  const remain=[];
  for(const ev of list){try{await setDoc(doc(db,'matches',state.id,'events',ev.eventId),ev);}catch(e){remain.push(ev);}}
  writePendingEvents(remain);cloudOnline=remain.length===0;setNetworkBadge();
  if(!remain.length){try{await save();}catch(e){}}
}
async function safeCloudSave(){
  if(!state?.id)return false;
  persistLocalState();
  if(!navigator.onLine){cloudOnline=false;setNetworkBadge();return false;}
  try{
    const cloud={...state,updatedAt:serverTimestamp()};
    await setDoc(doc(db,'matches',state.id),cloud,{merge:true});
    await setDoc(doc(db,'liveMatches',state.id),cloud,{merge:true});
    cloudOnline=true;setNetworkBadge();return true;
  }catch(e){cloudOnline=false;setNetworkBadge();return false;}
}
window.addEventListener('online',()=>{cloudOnline=true;setNetworkBadge();syncPending();});
window.addEventListener('offline',()=>{cloudOnline=false;setNetworkBadge();});
setInterval(()=>{syncPending();},15000);
function render(){if(!state)return;const target=Number(state.target||0);$("matchTitle").textContent=`${state.battingTeam} vs ${state.bowlingTeam}`;$("battingTeam").textContent=state.battingTeam;$("score").textContent=`${state.score||0}/${state.wickets||0}`;$("oversText").textContent=`${ballsText(state.legalBalls)} / ${state.maxOvers||15} overs`;$("crr").textContent=`CRR ${state.legalBalls?(state.score/(state.legalBalls/6)).toFixed(2):"0.00"}`;const rrr=target>0&&state.legalBalls<Number(state.maxOvers||15)*6?((target-state.score)/((Number(state.maxOvers||15)*6-state.legalBalls)/6)):0;$("rrr").textContent=target?`Target ${target} • RRR ${Math.max(0,rrr).toFixed(2)}`:`Target —`;$("matchMeta").textContent=`${state.season||2026} • ${state.stageName||"Match"} • ${state.status||"LIVE"}`;
 const ss=$("striker"),ns=$("nonStriker"),bw=$("bowler");ss.innerHTML=ns.innerHTML=bw.innerHTML="";(state.players||[]).forEach(p=>{const o=new Option(`${p.name}${p.out?" (OUT)":""}`,p.id);ss.add(o.cloneNode(true));ns.add(o.cloneNode(true));});(state.bowlers||[]).forEach(p=>bw.add(new Option(p.name,p.id)));ss.value=state.striker;ns.value=state.nonStriker;bw.value=state.bowler;$("batInfo").textContent=`${state.players?.find(p=>p.id===state.striker)?.runs||0} runs`;$("bowlInfo").textContent=`${state.bowlers?.find(p=>p.id===state.bowler)?.wickets||0} wicket(s)`;$("freeHitBadge").classList.toggle("hidden",!state.freeHit);$("bowlerChangeMsg").textContent=state.bowlerChangeRequired?`ওভার শেষ — নতুন বোলার নির্বাচন করুন (আগের: ${state.bowlers?.find(p=>p.id===state.bowler)?.name||""})`:`${state.freeHit?"FREE HIT • ":""}বর্তমান বোলার: ${state.bowlers?.find(p=>p.id===state.bowler)?.name||""}`;
 $("battingCard").innerHTML=`<table><tr><th>ব্যাটার</th><th>R</th><th>B</th><th>4s</th><th>6s</th></tr>${(state.players||[]).map(p=>`<tr><td>${esc(p.name)}${p.id===state.striker?" *":""}</td><td>${p.runs||0}</td><td>${p.balls||0}</td><td>${p.fours||0}</td><td>${p.sixes||0}</td></tr>`).join("")}</table>`;
 $("bowlingCard").innerHTML=`<table><tr><th>বোলার</th><th>O</th><th>R</th><th>W</th></tr>${(state.bowlers||[]).map(p=>`<tr><td>${esc(p.name)}</td><td>${ballsText(p.balls)}</td><td>${p.runs||0}</td><td>${p.wickets||0}</td></tr>`).join("")}</table>`;
 $("commentary").innerHTML=(state.commentary||[]).slice(-40).reverse().map(x=>`<div><b>${esc(x.over)}</b> — ${esc(x.text)}</div>`).join("");
 $("target").value=state.target||"";$("inningsNo").textContent=state.superOver?`Super Over • Innings ${state.inningsNo}`:`Innings ${state.inningsNo} of 2`;
 const done=state.status!=="LIVE",scoringLocked=done||!!state.bowlerChangeRequired;$("runButtons").querySelectorAll("button").forEach(b=>b.disabled=scoringLocked);document.querySelectorAll("[data-extra]").forEach(b=>b.disabled=scoringLocked);$("wicketBtn").disabled=scoringLocked;$("endInnings").disabled=done;$("startSecond").classList.toggle("hidden",state.status!=="INNINGS_BREAK"||state.inningsNo!==1);$("startSuper").classList.toggle("hidden",state.status!=="SUPER_OVER_READY");$("finishSuper").classList.toggle("hidden",!(state.status==="SUPER_OVER"));$("resultBox").classList.toggle("hidden",state.status!=="COMPLETED"&&state.status!=="SUPER_OVER_READY");$("resultText").textContent=state.resultText||"";
}
async function save(){return safeCloudSave();}
function selectedBatter(id){return (state.players||[]).find(p=>p.id===id);}
function commentaryLang(){return $("commentaryLang")?.value||"bn";}
function buildDismissalText(type,batter,fielder){const lang=commentaryLang(),name=batter.name,f=fielder?.name||"",bowler=state.bowlers.find(x=>x.id===state.bowler)?.name||"";if(lang==="en"){if(type==="caught")return `WICKET — ${name} c ${f} b ${bowler}`;if(type==="runOut")return `WICKET — ${name} Run Out by ${f}`;if(type==="stumped")return `WICKET — ${name} st ${f} b ${bowler}`;return `WICKET — ${name} ${dismissalNames[type]?.en||type}`;}if(type==="caught")return `উইকেট — ${name} ক্যাচ ${f}, বোলার ${bowler}`;if(type==="runOut")return `উইকেট — ${name} রান আউট, ফিল্ডার ${f}`;if(type==="stumped")return `উইকেট — ${name} স্টাম্পড ${f}, বোলার ${bowler}`;return `উইকেট — ${name} ${dismissalNames[type]?.bn||type}`;}
function openWicketModal(){if(!state||state.status!=="LIVE")return;const live=(state.players||[]).filter(p=>!p.out);$("dismissedBatter").innerHTML=live.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.id===state.striker?" (Striker)":""}</option>`).join("");$("fielder").innerHTML=`<option value="">ফিল্ডার নির্বাচন করুন</option>`+(state.bowlers||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("");$("dismissedBatter").value=state.striker||live[0]?.id||"";updateFielderVisibility();$("wicketModal").classList.remove("hidden");}
function closeWicketModal(){$("wicketModal").classList.add("hidden");}
function updateFielderVisibility(){const type=$("dismissalType")?.value,need=["caught","runOut","stumped"].includes(type);$("fielderBox")?.classList.toggle("hidden",!need);if($("fielderLabel"))$("fielderLabel").textContent=type==="stumped"?"Wicketkeeper / Fielder":type==="caught"?"Catcher / Fielder":"Fielder";}
async function confirmWicket(){const batter=selectedBatter($("dismissedBatter").value),type=$("dismissalType").value,fielder=(state.bowlers||[]).find(x=>x.id===$("fielder").value);if(!batter){alert("আউট হওয়া ব্যাটার নির্বাচন করুন।");return;}if(["caught","runOut","stumped"].includes(type)&&!fielder){alert("এই dismissal-এর জন্য ফিল্ডার নির্বাচন করুন।");return;}if(state.freeHit&&bowlerWicketTypes.includes(type)){alert("FREE HIT-এ Bowled/Caught/LBW/Stumped/Hit Wicket আউট হবে না। Run Out/Obstructing/Hit Twice/Timed Out/Retired Out নির্বাচন করুন।");return;}closeWicketModal();await applyWicket(type,batter,fielder);}
async function recordPlayerStats(event){const id=event.strikerId;if(!id)return;const ref=doc(db,"players",id),snap=await getDoc(ref),cur=snap.exists()?snap.data():{id,name:event.batterName||id};await setDoc(ref,{...cur,id,name:cur.name||event.batterName||id,totalRuns:(cur.totalRuns||0)+(event.batterRuns||0),totalBalls:(cur.totalBalls||0)+(event.legal?1:0),totalFours:(cur.totalFours||0)+(event.batterRuns===4?1:0),totalSixes:(cur.totalSixes||0)+(event.batterRuns===6?1:0)},{merge:true});}
async function recordBowlerStats(event){const id=event.bowlerId;if(!id)return;const ref=doc(db,"players",id),snap=await getDoc(ref),cur=snap.exists()?snap.data():{id,name:event.bowlerName||id};await setDoc(ref,{...cur,id,name:cur.name||event.bowlerName||id,totalBowlingBalls:(cur.totalBowlingBalls||0)+(event.legal?1:0),totalBowlingRuns:(cur.totalBowlingRuns||0)+(event.bowlerRuns||0),totalWickets:(cur.totalWickets||0)+(event.bowlerWicket?1:0)},{merge:true});}
async function recordFieldingStats(event){const id=event.fielderId;if(!id)return;const ref=doc(db,"players",id),snap=await getDoc(ref),cur=snap.exists()?snap.data():{id,name:event.fielderName||id};const patch={...cur,id,name:cur.name||event.fielderName||id,fieldingCatches:(cur.fieldingCatches||0)+(event.dismissalType==="caught"?1:0),fieldingStumpings:(cur.fieldingStumpings||0)+(event.dismissalType==="stumped"?1:0),fieldingRunOuts:(cur.fieldingRunOuts||0)+(event.dismissalType==="runOut"?1:0)};patch.fieldingDismissals=(patch.fieldingCatches||0)+(patch.fieldingStumpings||0)+(patch.fieldingRunOuts||0);await setDoc(ref,patch,{merge:true});}
async function applyWicket(type,batter,fielder){if(!state||state.status!=="LIVE")return;if(state.bowlerChangeRequired){alert("৬টি legal ball শেষ হয়েছে। আগে নতুন বোলার নির্বাচন করুন।");return;}if(state.freeHit&&bowlerWicketTypes.includes(type)){alert("FREE HIT-এ এই dismissal বৈধ নয়।");return;}const before=clone(state),bowler=state.bowlers.find(x=>x.id===state.bowler);if(!bowler){alert("আগে বোলার নির্বাচন করুন।");return;}state.wickets++;batter.out=true;const credited=bowlerWicketTypes.includes(type);if(credited)bowler.wickets++;if(type!=="timedOut"&&type!=="retiredOut"){batter.balls++;state.legalBalls++;bowler.balls++;state.freeHit=false;if(state.legalBalls%6===0)state.bowlerChangeRequired=true;}if(batter.id===state.striker){state.striker=(state.players||[]).find(p=>!p.out&&p.id!==state.nonStriker)?.id||"";}else if(batter.id===state.nonStriker){state.nonStriker=(state.players||[]).find(p=>!p.out&&p.id!==state.striker)?.id||"";}const ev={eventId:newEventId(),type:"wicket",dismissalType:type,dismissedBatterId:batter.id,dismissedBatter:batter.name,fielderId:fielder?.id||"",fielderName:fielder?.name||"",batterName:batter.name,batterRuns:0,bowlerId:bowler.id,bowlerName:bowler.name,bowlerRuns:0,legal:type!=="timedOut"&&type!=="retiredOut",bowlerWicket:credited,strikerId:batter.id,inningsNo:state.inningsNo,over:ballsText(before.legalBalls),text:buildDismissalText(type,batter,fielder),createdAt:new Date().toISOString()};state.commentary.push(ev);eventStack.push(before);persistLocalState();const synced=await syncEvent(ev);if(synced)try{await recordFieldingStats(ev);}catch(e){}await checkInningsEnd();await save();render();}
async function apply(type,value=0){if(!state||state.status!=="LIVE")return;if(state.bowlerChangeRequired){alert("৬টি legal ball শেষ হয়েছে। আগে নতুন বোলার নির্বাচন করুন।");return;}const before=clone(state),striker=selectedBatter(state.striker),bowler=state.bowlers.find(x=>x.id===state.bowler);if(!striker||!bowler){alert("আগে ব্যাটার ও বোলার নির্বাচন করুন।");return;}let legal=true,batterRuns=0,extra=0,text="";if(type==="run"){batterRuns=value;text=value===4?"FOUR":value===6?"SIX":`${value} run`;}if(type==="wide"){legal=false;extra=1;state.extras.wide++;text="Wide";}if(type==="noBall"){legal=false;extra=1;state.extras.noBall++;state.freeHit=true;text="NO BALL • FREE HIT";}if(type==="bye"){extra=value;state.extras.bye+=value;text=`Bye ${value}`;}if(type==="legBye"){extra=value;state.extras.legBye+=value;text=`Leg bye ${value}`;}
 state.score+=batterRuns+extra;striker.runs+=batterRuns;if(legal)striker.balls++;if(batterRuns===4)striker.fours++;if(batterRuns===6)striker.sixes++;bowler.runs+=batterRuns+((type==="wide"||type==="noBall")?1:0);if(legal){state.legalBalls++;bowler.balls++;state.freeHit=false;if(state.legalBalls%6===0)state.bowlerChangeRequired=true;}if((batterRuns+extra)%2===1)[state.striker,state.nonStriker]=[state.nonStriker,state.striker];if(legal&&state.legalBalls%6===0)[state.striker,state.nonStriker]=[state.nonStriker,state.striker];const bowlerRuns=(type==="wide"||type==="noBall")?1:(type==="bye"||type==="legBye"?0:batterRuns);const ev={eventId:newEventId(),type,batterRuns,bowlerRuns,legal,strikerId:striker.id,batterName:striker.name,bowlerId:bowler.id,bowlerName:bowler.name,inningsNo:state.inningsNo,over:ballsText(before.legalBalls),text,createdAt:new Date().toISOString()};state.commentary.push(ev);eventStack.push(before);persistLocalState();const synced=await syncEvent(ev);if(synced){try{await recordPlayerStats(ev);}catch(e){}try{await recordBowlerStats(ev);}catch(e){}}await checkInningsEnd();await save();render();}
function snapshotCurrent(){return {inningsNo:state.inningsNo,battingTeamId:state.battingTeamId,battingTeam:state.battingTeam,bowlingTeamId:state.bowlingTeamId,bowlingTeam:state.bowlingTeam,score:state.score,wickets:state.wickets,legalBalls:state.legalBalls,maxOvers:state.maxOvers,target:state.target,extras:state.extras,players:state.players,bowlers:state.bowlers,commentary:state.commentary,status:state.status};}
async function checkInningsEnd(){if(!state)return;const maxBalls=Number(state.maxOvers||15)*6,allOut=state.wickets>=Math.max(1,(state.players||[]).length-1),targetReached=state.target>0&&state.score>=state.target;if(targetReached){state.status="COMPLETED";state.winnerTeamId=state.battingTeamId;state.winnerTeamName=state.battingTeam;state.resultText=`${state.battingTeam} won by ${Math.max(1,(state.players||[]).length-state.wickets)} wicket(s)`;await finalizeTournament();return;}if(state.legalBalls>=maxBalls||allOut){if(state.inningsNo===1&&!state.superOver){state.status="INNINGS_BREAK";return;}if(!state.superOver){state.status="COMPLETED";if(state.score>state.target-1){state.winnerTeamId=state.battingTeamId;state.winnerTeamName=state.battingTeam;state.resultText=`${state.battingTeam} won by ${state.score-(state.target-1)} run(s)`;}else if(state.score===state.target-1){state.status="SUPER_OVER_READY";state.resultText="Match tied — Super Over required";}else{state.winnerTeamId=state.bowlingTeamId;state.winnerTeamName=state.bowlingTeam;state.resultText=`${state.bowlingTeam} won by ${Math.max(1,(state.target-1)-state.score)} run(s)`;}if(state.status==="COMPLETED")await finalizeTournament();return;}await finishSuperOverInnings();}}
async function startSecondInnings(){if(state.status!=="INNINGS_BREAK"||state.inningsNo!==1)return;state.inningsHistory=[...(state.inningsHistory||[]),snapshotCurrent()];const batList=players.filter(p=>p.teamId===state.team2Id),bowlList=players.filter(p=>p.teamId===state.team1Id);const inn=makeInnings(state.team2Id,state.team2Name,state.team1Id,state.team1Name,batList,bowlList,state.maxOvers,state.score+1,2,false);Object.assign(state,inn);state.status="LIVE";state.inningsNo=2;await save();render();}
async function startSuperOver(){if(state.status!=="SUPER_OVER_READY")return;state.superOver={phase:1,scores:{[state.team1Id]:0,[state.team2Id]:0},balls:6};const batList=players.filter(p=>p.teamId===state.team1Id),bowlList=players.filter(p=>p.teamId===state.team2Id);const inn=makeInnings(state.team1Id,state.team1Name,state.team2Id,state.team2Name,batList,bowlList,1,0,1,true);Object.assign(state,inn);state.status="SUPER_OVER";state.inningsNo=1;state.commentary=[{over:"SUPER",text:`Super Over শুরু — ${state.team1Name} ব্যাটিং`,createdAt:new Date().toISOString()}];await save();render();}
async function finishSuperOverInnings(){const phase=state.superOver.phase;state.superOver.scores[state.battingTeamId]=state.score;state.inningsHistory=[...(state.inningsHistory||[]),snapshotCurrent()];if(phase===1){state.superOver.phase=2;const batList=players.filter(p=>p.teamId===state.team2Id),bowlList=players.filter(p=>p.teamId===state.team1Id);const inn=makeInnings(state.team2Id,state.team2Name,state.team1Id,state.team1Name,batList,bowlList,1,0,2,true);Object.assign(state,inn);state.status="SUPER_OVER";await save();render();return;}const a=state.superOver.scores[state.team1Id]||0,b=state.superOver.scores[state.team2Id]||0;if(a===b){state.status="SUPER_OVER_READY";state.resultText="Super Over tied — start another Super Over";state.superOver.phase=1;await save();render();return;}state.status="COMPLETED";state.winnerTeamId=a>b?state.team1Id:state.team2Id;state.winnerTeamName=a>b?state.team1Name:state.team2Name;state.resultText=`${state.winnerTeamName} won the Super Over (${Math.max(a,b)}–${Math.min(a,b)})`;await finalizeTournament();await save();render();}
async function recordMatchStatsOnce(){if(state.statsRecorded)return;const snap=await getDocs(collection(db,"matches",state.id,"events"));const by={};snap.docs.forEach(d=>{const e=d.data();if(e.strikerId){const x=by[e.strikerId] ||= {runs:0,balls:0,fours:0,sixes:0,wickets:0,bowlingBalls:0,bowlingRuns:0,catches:0,stumpings:0,runOuts:0};x.runs+=(e.batterRuns||0);x.balls+=e.legal?1:0;x.fours+=e.batterRuns===4?1:0;x.sixes+=e.batterRuns===6?1:0;}if(e.bowlerId){const x=by[e.bowlerId] ||= {runs:0,balls:0,fours:0,sixes:0,wickets:0,bowlingBalls:0,bowlingRuns:0,catches:0,stumpings:0,runOuts:0};x.bowlingBalls+=e.legal?1:0;x.bowlingRuns+=(e.bowlerRuns||0);x.wickets+=e.bowlerWicket?1:0;}if(e.fielderId){const x=by[e.fielderId] ||= {runs:0,balls:0,fours:0,sixes:0,wickets:0,bowlingBalls:0,bowlingRuns:0,catches:0,stumpings:0,runOuts:0};x.catches+=e.dismissalType==="caught"?1:0;x.stumpings+=e.dismissalType==="stumped"?1:0;x.runOuts+=e.dismissalType==="runOut"?1:0;}});for(const [id,x] of Object.entries(by)){const ref=doc(db,"players",id),ps=await getDoc(ref),cur=ps.exists()?ps.data():{id};await setDoc(ref,{...cur,id,totalRuns:(cur.totalRuns||0)+x.runs,totalBalls:(cur.totalBalls||0)+x.balls,totalFours:(cur.totalFours||0)+x.fours,totalSixes:(cur.totalSixes||0)+x.sixes,totalBowlingBalls:(cur.totalBowlingBalls||0)+x.bowlingBalls,totalBowlingRuns:(cur.totalBowlingRuns||0)+x.bowlingRuns,totalWickets:(cur.totalWickets||0)+x.wickets,fieldingCatches:(cur.fieldingCatches||0)+x.catches,fieldingStumpings:(cur.fieldingStumpings||0)+x.stumpings,fieldingRunOuts:(cur.fieldingRunOuts||0)+x.runOuts,fieldingDismissals:(cur.fieldingDismissals||0)+x.catches+x.stumpings+x.runOuts},{merge:true});}state.statsRecorded=true;await setDoc(doc(db,"matches",state.id),{statsRecorded:true},{merge:true});}
async function recordHatTricksOnce(){
 if(state.hatTricksRecorded)return;
 const snap=await getDocs(collection(db,"matches",state.id,"events"));
 const evs=snap.docs.map(d=>d.data()).sort((a,b)=>String(a.createdAt||"").localeCompare(String(b.createdAt||"")));
 const hat={bowler:[],batter:[],fielder:[]};
 let bowlerRun=0,bowlerId="";
 let batterRun=0,batterId="";
 let fieldRun=0,fieldId="";
 for(const e of evs){
   if(e.type==="wicket"){
     const legal=e.legal!==false;
     const credited=!!e.bowlerWicket;
     // Bowler hat-trick: three consecutive legal deliveries from the same bowler that are credited wickets.
     if(legal){
       if(credited && e.bowlerId===bowlerId) bowlerRun++; else if(credited){bowlerId=e.bowlerId;bowlerRun=1;} else {bowlerId=e.bowlerId||"";bowlerRun=0;}
       if(bowlerRun===3){hat.bowler.push({playerId:e.bowlerId,playerName:e.bowlerName||e.bowlerId,over:e.over||"",inningsNo:e.inningsNo||1});bowlerRun=0;}
     }
     // Fielder hat-trick: three consecutive dismissals credited to the same fielder.
     if(e.fielderId){if(e.fielderId===fieldId)fieldRun++;else{fieldId=e.fielderId;fieldRun=1;}if(fieldRun===3){hat.fielder.push({playerId:e.fielderId,playerName:e.fielderName||e.fielderId,over:e.over||"",inningsNo:e.inningsNo||1});fieldRun=0;}}
     else {fieldId="";fieldRun=0;}
   } else if(e.legal){
     // Batter hat-trick: three consecutive legal deliveries hit for 4 or 6 by the same batter.
     if(e.strikerId===batterId && (e.batterRuns===4||e.batterRuns===6)) batterRun++;
     else {batterId=e.strikerId||"";batterRun=(e.batterRuns===4||e.batterRuns===6)?1:0;}
     if(batterRun===3){hat.batter.push({playerId:e.strikerId,playerName:e.batterName||e.strikerId,over:e.over||"",inningsNo:e.inningsNo||1});batterRun=0;}
     // A legal non-wicket ball by another bowler breaks that bowler's wicket sequence.
     if(e.bowlerId!==bowlerId){bowlerId=e.bowlerId||"";bowlerRun=0;}
   }
 }
 for(const type of ["bowler","batter","fielder"]){
   for(const h of hat[type]){
     const ref=doc(db,"players",h.playerId),ps=await getDoc(ref),cur=ps.exists()?ps.data():{id:h.playerId,name:h.playerName};
     const key=type==="bowler"?"bowlingHatTricks":type==="batter"?"battingHatTricks":"fieldingHatTricks";
     await setDoc(ref,{...cur,id:h.playerId,name:cur.name||h.playerName,[key]:(cur[key]||0)+1},{merge:true});
   }
 }
 await setDoc(doc(db,"matches",state.id),{hatTricks:hat,hatTricksRecorded:true},{merge:true});
 state.hatTricksRecorded=true;state.hatTricks=hat;
}
async function finalizeTournament(){if(!state.winnerTeamId)return;await recordMatchStatsOnce();await recordHatTricksOnce();const ref=doc(db,"tournaments",String(state.season)),snap=await getDoc(ref),t=snap.exists()?snap.data():{season:state.season,slots:Array(16).fill(""),winners:{},matchIds:{}};const winners={...(t.winners||{})},matchIds={...(t.matchIds||{})};if(state.bracketKey){winners[state.bracketKey]=state.winnerTeamId;matchIds[state.bracketKey]=state.id;}if(state.stage==="FINAL")t.championTeamId=state.winnerTeamId;t.winners=winners;t.matchIds=matchIds;await setDoc(ref,t,{merge:true});}
async function undo(){const prev=eventStack.pop();if(!prev){alert("এই session-এ undo করার মতো event নেই");return;}state=prev;await save();render();}
async function loadSetupData(){
 const [ts,ps,ms]=await Promise.all([getDocs(collection(db,"teams")),getDocs(collection(db,"players")),getDocs(collection(db,"members"))]);
 teams=ts.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||"").localeCompare(b.name||""));
 players=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||"").localeCompare(b.name||""));
 members=ms.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||"").localeCompare(b.name||""));
 const opts=teams.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}${t.shortName?` (${esc(t.shortName)})`:""}</option>`).join("");
 $("team1").innerHTML=`<option value="">প্রথম দল</option>${opts}`;$("team2").innerHTML=`<option value="">দ্বিতীয় দল</option>${opts}`;
 $("newPlayerTeam").innerHTML=`<option value="">দল</option>${opts}`;$("editPlayerSelect").innerHTML=`<option value="">খেলোয়াড়</option>${players.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("")}`;
 $("memberTeam").innerHTML=`<option value="">দল নেই / প্রযোজ্য নয়</option>${opts}`;$("teamCount").textContent=`${teams.length} / 16 দল`;renderMemberAdmin();
}
function resetMemberForm(){editingMemberId="";["memberName","memberRole","memberPhone","memberEmail","memberAddress","memberFee","memberNote"].forEach(id=>{if($(id))$(id).value="";});if($("memberSeason"))$("memberSeason").value="2026";if($("memberFeeStatus"))$("memberFeeStatus").value="বাকি";if($("memberTeam"))$("memberTeam").value="";if($("memberSave"))$("memberSave").textContent="সদস্য Save করুন";if($("memberCancel"))$("memberCancel").classList.add("hidden");}
function renderMemberAdmin(){const box=$("memberAdminTable");if(!box)return;box.innerHTML=members.length?`<div class="table-wrap"><table><tr><th>নাম</th><th>ভূমিকা</th><th>ফোন</th><th>দল</th><th>Season</th><th>Fee</th><th>Status</th><th>Action</th></tr>${members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.role)}</td><td>${esc(m.phone)}</td><td>${esc(m.teamName||"")}</td><td>${esc(m.season||"")}</td><td>${esc(m.fee||"")}</td><td>${esc(m.feeStatus||"")}</td><td><button data-med="${esc(m.id)}">Edit</button> <button data-mdel="${esc(m.id)}">Delete</button></td></tr>`).join("")}</table></div>`:'<p class="muted">এখনও কোনো সদস্যের তথ্য নেই।</p>';box.querySelectorAll("[data-med]").forEach(b=>b.onclick=()=>editMember(b.dataset.med));box.querySelectorAll("[data-mdel]").forEach(b=>b.onclick=()=>deleteMember(b.dataset.mdel));if($("memberCount"))$("memberCount").textContent=`${members.length} জন`;}
function editMember(id){const m=members.find(x=>x.id===id);if(!m)return;editingMemberId=id;$("memberName").value=m.name||"";$("memberRole").value=m.role||"";$("memberPhone").value=m.phone||"";$("memberEmail").value=m.email||"";$("memberAddress").value=m.address||"";$("memberFee").value=m.fee||"";$("memberFeeStatus").value=m.feeStatus||"বাকি";$("memberSeason").value=m.season||"2026";$("memberNote").value=m.note||"";$("memberTeam").value=m.teamId||"";$("memberSave").textContent="সদস্যের তথ্য Update করুন";$("memberCancel").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
async function saveMember(){const name=$("memberName").value.trim();if(!name){$("memberMsg").textContent="সদস্যের নাম দিন।";return;}const team=teams.find(t=>t.id===$("memberTeam").value);const data={name,role:$("memberRole").value.trim(),phone:$("memberPhone").value.trim(),email:$("memberEmail").value.trim().toLowerCase(),address:$("memberAddress").value.trim(),fee:$("memberFee").value.trim(),feeStatus:$("memberFeeStatus").value,season:Number($("memberSeason").value||2026),note:$("memberNote").value.trim(),teamId:team?.id||"",teamName:team?.name||"",updatedAt:serverTimestamp()};try{const id=editingMemberId||`member-${Date.now()}`;if(editingMemberId)await updateDoc(doc(db,"members",id),data);else await setDoc(doc(db,"members",id),{id,...data,createdAt:serverTimestamp()});await setDoc(doc(db,"memberDirectory",id),{memberId:id,name:data.name,role:data.role,teamName:data.teamName,paidAmount:data.fee||0,paymentStatus:data.feeStatus||"",season:data.season,updatedAt:serverTimestamp()},{merge:true});$("memberMsg").textContent="সদস্যের তথ্য Save হয়েছে এবং public list update হয়েছে.";resetMemberForm();await loadSetupData();}catch(e){$("memberMsg").textContent=`Save হয়নি: ${e.message}`;}}
async function deleteMember(id){const m=members.find(x=>x.id===id);if(!m||!confirm(`“${m.name||id}” সদস্যের তথ্য Delete করতে চান?`))return;try{await deleteDoc(doc(db,"members",id));await deleteDoc(doc(db,"memberDirectory",id));await loadSetupData();}catch(e){alert(`Delete হয়নি: ${e.message}`);}}
async function createMatch(){const t1=$("team1").value,t2=$("team2").value;if(!t1||!t2||t1===t2){$("setupMsg").textContent="দুটি আলাদা দল নির্বাচন করুন।";return;}const overs=oversValue();if(!overs||overs<1||overs>50){$("setupMsg").textContent="Overs 1–50 এর মধ্যে দিন।";return;}const season=Number($("season").value||2026),stage=$("stage").value,bracketKey=$("bracketKey").value;const a=teams.find(t=>t.id===t1),b=teams.find(t=>t.id===t2),p1=players.filter(p=>p.teamId===t1),p2=players.filter(p=>p.teamId===t2);if(p1.length<2||p2.length<2){$("setupMsg").textContent="দুই দলে অন্তত ২ জন করে খেলোয়াড় প্রয়োজন।";return;}let id=$("matchId").value.trim();if(!id)id=`${season}-${stage.toLowerCase()}-${slug(a.name)}-${slug(b.name)}`;const m=newMatch(id,t1,t2,overs,p1,p2,{season,stage,stageName:stageNames[stage]||stage,team1Name:a.name,team2Name:b.name,bracketKey});await setDoc(doc(db,"matches",id),m);await setDoc(doc(db,"liveMatches",id),m);state=m;eventStack=[];localStorage.setItem("vcajActiveMatchId",id);$("activeMatchId").value=id;if(unsub)unsub();unsub=onSnapshot(doc(db,"matches",id),s=>{if(s.exists()){state=s.data();render();}});render();$("setupMsg").textContent=`${id} তৈরি হয়েছে।`;}
$("overs").onchange=()=>$("customOvers").classList.toggle("hidden",$("overs").value!=="custom");$("refreshSetup").onclick=loadSetupData;
$("addTeam").onclick=async()=>{const name=$("newTeamName").value.trim(),shortName=$("newTeamShort").value.trim();if(!name){$("teamMsg").textContent="দলের নাম দিন।";return;}if(teams.length>=16){$("teamMsg").textContent="১৬টি দলের সীমা পূর্ণ হয়েছে।";return;}const id=`team-${Date.now()}`;await setDoc(doc(db,"teams",id),{id,name,shortName,playersCount:0,season:2026,createdAt:serverTimestamp()});$("newTeamName").value=$("newTeamShort").value="";$("teamMsg").textContent="দল Save হয়েছে।";await loadSetupData();};
$("addPlayer").onclick=async()=>{const name=$("newPlayerName").value.trim(),teamId=$("newPlayerTeam").value;if(!name||!teamId){$("playerMsg").textContent="নাম ও দল নির্বাচন করুন।";return;}const id=`player-${Date.now()}`,team=teams.find(t=>t.id===teamId);await setDoc(doc(db,"players",id),{id,name,teamId,teamName:team?.name||"",totalRuns:0,totalBalls:0,totalFours:0,totalSixes:0,totalMatches:0,totalWickets:0,createdAt:serverTimestamp()});if(team)await setDoc(doc(db,"teams",teamId),{playersCount:(team.playersCount||0)+1},{merge:true});$("newPlayerName").value="";$("playerMsg").textContent="খেলোয়াড় Save হয়েছে।";await loadSetupData();};
$("editPlayer").onclick=async()=>{const id=$("editPlayerSelect").value,name=$("editPlayerName").value.trim();if(!id||!name){$("editPlayerMsg").textContent="খেলোয়াড় ও নতুন নাম দিন।";return;}await updateDoc(doc(db,"players",id),{name,updatedAt:serverTimestamp()});$("editPlayerMsg").textContent="নাম আপডেট হয়েছে।";await loadSetupData();$("editPlayerSelect").value=id;$("editPlayerName").value=name;};$("editPlayerSelect").onchange=()=>{const p=players.find(x=>x.id===$("editPlayerSelect").value);if(p)$("editPlayerName").value=p.name||"";};
$("memberSave").onclick=saveMember;$("memberCancel").onclick=resetMemberForm;$("createMatch").onclick=createMatch;$("loadMatch").onclick=()=>loadMatch($("activeMatchId").value.trim());$("bowler").onchange=e=>{if(!state)return;const next=e.target.value;if(state.bowlerChangeRequired&&next===state.bowler){e.target.value=state.bowler;alert("নতুন বোলার নির্বাচন করুন।");return;}state.bowler=next;if(state.bowlerChangeRequired){state.bowlerChangeRequired=false;state.bowlerChangeFromId="";}save();render();};$("startSecond").onclick=startSecondInnings;$("startSuper").onclick=startSuperOver;$("finishSuper").onclick=finishSuperOverInnings;
$("runButtons").innerHTML=[0,1,2,3,4,5,6].map(n=>`<button data-run="${n}" class="${n===4||n===6?"accent":""}">${n}</button>`).join("");document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>apply("run",Number(b.dataset.run)));document.querySelectorAll("[data-extra]").forEach(b=>b.onclick=()=>apply(b.dataset.extra,b.dataset.extra==="bye"||b.dataset.extra==="legBye"?1:0));$("wicketBtn").onclick=openWicketModal;$("closeWicket").onclick=closeWicketModal;$("cancelWicket").onclick=closeWicketModal;$("confirmWicket").onclick=confirmWicket;$("dismissalType").onchange=updateFielderVisibility;$("striker").onchange=e=>{if(state){state.striker=e.target.value;save();}};$("nonStriker").onchange=e=>{if(state){state.nonStriker=e.target.value;save();}};$("target").onchange=e=>{if(state){state.target=Number(e.target.value||0);save();}};$("undoBtn").onclick=undo;$("endInnings").onclick=async()=>{if(state?.status==="LIVE"){state.legalBalls=Number(state.maxOvers||15)*6;await checkInningsEnd();await save();render();}};
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value,$("password").value);}catch(e){$("loginMsg").textContent=e.message;}};
$("memberLoginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,phoneToAuthEmail($("memberLoginPhone").value.trim()),$("memberLoginPassword").value);location.href="member-panel.html";}catch(e){$("memberLoginMsg").textContent="Member Login হয়নি: "+(e.code||e.message);}};$("logoutBtn").onclick=()=>signOut(auth);
async function loadMatch(id){id=(id||"").trim();if(!id)return;localStorage.setItem("vcajActiveMatchId",id);try{const snap=await getDoc(doc(db,"matches",id));if(!snap.exists())throw new Error("Match পাওয়া যায়নি।");state=snap.data();persistLocalState();}catch(e){const local=readLocalState(id);if(!local){alert("Firebase unavailable এবং এই ম্যাচের local backup পাওয়া যায়নি।");return;}state=local;cloudOnline=false;alert("Firebase এখন পাওয়া যাচ্ছে না। Local backup থেকে match resume হয়েছে। Internet ফিরলে automatic sync হবে।");}eventStack=[];render();setNetworkBadge();if(unsub)unsub();unsub=onSnapshot(doc(db,"matches",id),s=>{if(s.exists()){state=s.data();persistLocalState();render();setNetworkBadge();syncPending();}},err=>{cloudOnline=false;setNetworkBadge();});syncPending();}
document.getElementById('backupBtn')?.addEventListener('click',()=>{
  if(!state?.id)return;
  persistLocalState();
  const payload={version:1,exportedAt:new Date().toISOString(),match:state,pendingEvents:pendingEvents()};
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});
  const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`VIVEKANANDA CRICKET ASSOCIATION OF JELIAKHALI-${state.id}-backup.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
});

onAuthStateChanged(auth,async user=>{if(user&&isAdmin(user)){$("loginCard").classList.add("hidden");$("scorerApp").classList.remove("hidden");await loadSetupData();setNetworkBadge();const q=new URLSearchParams(location.search);if(q.get("stage"))$("stage").value=q.get("stage");if(q.get("bracket"))$("bracketKey").value=q.get("bracket");if(q.get("t1"))$("team1").value=q.get("t1");if(q.get("t2"))$("team2").value=q.get("t2");const saved=localStorage.getItem("vcajActiveMatchId");if(saved&&!q.get("t1")){$("activeMatchId").value=saved;await loadMatch(saved);}}else{$("loginCard").classList.remove("hidden");$("scorerApp").classList.add("hidden");}});
